{
    "server_logfile_path": "E:\\3MF-Analyzer\\data\\evaluation\\prusa\\snapshots\\CS-1101\\local-server.log",
    "states": {
        "00 program-not-started": {
            "timestamp": 1665927038.2931676
        },
        "01 program-started": {
            "timestamp": 1665927042.468831
        },
        "02 program-not-loaded": {
            "timestamp": 1665927042.6396706,
            "related_exception": [
                "<class 'selenium.common.exceptions.WebDriverException'>",
                "An unknown error occurred in the remote end while processing the command.",
                null,
                null
            ]
        }
    }
}