{
    "server_logfile_path": "E:\\3MF-Analyzer\\data\\evaluation\\cura\\snapshots\\DOS-FUZ-SAVITAR-0\\local-server.log",
    "states": {
        "00 program-not-started": {
            "timestamp": 1665863277.9928882
        },
        "01 program-started": {
            "timestamp": 1665863283.2150683
        },
        "02 program-loaded": {
            "timestamp": 1665863299.2200446
        },
        "03 program-prepared": {
            "timestamp": 1665863304.4274764,
            "screenshot": true,
            "snapshot": true
        },
        "05 model-not-loaded": {
            "timestamp": 1665863317.5916677,
            "screenshot": true,
            "snapshot": true,
            "related_exception": [
                "<class 'selenium.common.exceptions.WebDriverException'>",
                "An unknown error occurred in the remote end while processing the command.",
                null,
                null
            ]
        },
        "06 program-stopped": {
            "timestamp": 1665863343.0079935
        }
    }
}